version: '3.8' # Docker Compose file format version

services:
   openplc:
      # Build directly from the OpenPLC GitHub repository's master branch
      build: https://github.com/thiagoralves/OpenPLC_v3.git#master
      container_name: openplc-controller
      ports:
        - "502:502"   # Modbus TCP
        - "8080:8080" # OpenPLC Web UI
      volumes:
        # This maps a host folder to the /docker_persistent volume defined in the official Dockerfile
        # This ensures your OpenPLC programs and configurations are saved persistently on your VM.
        - ./openplc_data:/docker_persistent
      restart: always
      networks:
        - scada_net # Connects this container to our custom network

  scadabr:
    build:
      context: ./scadabr # Dockerfile folder for ScadaBR
    container_name: scadabr-hmi # A friendly name for the container
    ports:
      - "9090:8080" # Map host port 9090 to container port 8080 (ScadaBR's default Tomcat port)
                   # We use 9090 on the host to avoid conflict with OpenPLC's 8080
    depends_on:
      - openplc # Ensures OpenPLC starts before ScadaBR
    restart: always
    networks:
      - scada_net # Connects this container to our custom network

networks:
  scada_net: # Define a custom bridge network for containers to communicate with each other
    driver: bridge
